let mySprite = sprites.create(assets.image`myImage`, SpriteKind.Player)
controller.moveSprite(mySprite)
music.baDing.play()
tiles.setCurrentTilemap(tilemap`level1`)
scene.cameraFollowSprite(mySprite)
